# Generated by Django 3.2.8 on 2022-06-27 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20220627_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email_verification',
        ),
    ]
